create table if not exists s_mongo_platform_core_order_equity_order_info (
    id string comment '订单id'
    ,version string comment 'None'
    ,orderNo string comment '订单编号'
    ,businessIdentifier string comment '业务线'
    ,orderType string comment '订单类型，{@link com.meow.platform.enums.order.OrderType}'
    ,subOrderType string comment '{@link EquitySubOrderType}
      子订单类型
      当orderType = EQ'
    ,parentFlag string comment '父子订单，1：父订单 0：子订单 （默认1）'
    ,parentOrderNo string comment '父订单编号'
    ,shopId string comment '店铺id'
    ,shopCode string comment '所属店铺'
    ,shopName string comment '店铺名称'
    ,shopAvatar string comment '店铺头像'
    ,merchantCode string comment '商家代码'
    ,merchantType string comment '商家类型 {@link com.meow.platform.enums.merchant.MerchantType}'
    ,merchantId string comment '商家id'
    ,merchantUserId string comment '商家所属用户id'
    ,merchantUserAvatar string comment '商家用户头像'
    ,merchantName string comment '商家用户名称'
    ,merchantPhone string comment '商家联系电话'
    ,merchantLevel string comment '商家级别'
    ,userId string comment '购买用户id'
    ,userName string comment '购买用户名称'
    ,userAvatar string comment '购买用户头像'
    ,orderChannel string comment '订单渠道，IOS：IOS，ANDROID：安卓 {@link com.meow.platform.enums.order'
    ,shippingType string comment '配送方式，1：快递，2：门店自提 {@link com.meow.platform.enums.order.Shippi'
    ,shippingAddress string comment '订单地址'
    ,logisticsCompanyName string comment '物流公司名'
    ,logisticsNo string comment '物流单号'
    ,countryCode string comment '订单地址国家代码'
    ,provinceCode string comment '订单地址省代码'
    ,cityCode string comment '市代码'
    ,countyCode string comment '区代码'
    ,subdistrictCode string comment '地址街道社区代码'
    ,address string comment '详细地址'
    ,shipTo string comment '收货人'
    ,shipToPhoneNo string comment '收货人电话'
    ,payType string comment '参考 {@link OrderPayType}
      支付方式，WX：微信，ZFB：支付宝， OFFLINE: 线'
    ,totalPrice string comment '订单金额'
    ,payAmount string comment '订单实付金额'
    ,reduceAmount string comment '优惠金额'
    ,couponInfos string comment '优惠券信息'
    ,promotionInfo string comment '优惠信息'
    ,deductionAmount string comment '抵扣金额'
    ,shippingFee string comment '运费'
    ,transactionNo string comment '第三方支付流水号'
    ,payOrderNo string comment '支付流水号（order_pay_info中的payOrderInfo）'
    ,userRemark string comment '用户下单备注'
    ,userReservedMobile string comment '买家手机号（用户预留手机号）'
    ,merchantRemark string comment '商家备注'
    ,orderStatus string comment '订单状态 10：待支付，100：待接单，110：待服务，120：服务中，130：商家确认完成，140：用户确认完成，15'
    ,commentStatus string comment '评价状态 WAIT_COMMENT：未评价 COMMENTED：已评价'
    ,isRefund string comment '是否退款，true：已退款，false：未退款'
    ,userCancelReason string comment '用户取消原因'
    ,merchantCancelReason string comment '商家取消原因'
    ,userDeleteFlag string comment '用户删除，true：已删除，false：未删除'
    ,merchantDeleteFlag string comment '商家删除，true：已删除，false：未删除'
    ,orderTime string comment '下单时间'
    ,orderCancelTime string comment '取消时间'
    ,orderPayTime string comment '支付时间'
    ,orderReceiveTime string comment '接单时间'
    ,merchantConfirmTime string comment '商家确认时间'
    ,orderDeliveryTime string comment '发货时间'
    ,orderCloseTime string comment '交易关闭时间'
    ,orderCompleteTime string comment '订单完成时间'
    ,orderRefundTime string comment '退款时间'
    ,orderItemList string comment '订单项列表'
    ,verifyBrand string comment '核销品牌'
    ,createTime string comment '创建时间'
    ,updateTime string comment '更新时间'
    ,shop string comment '店铺信息'
    ,affiliatedShopId string comment '挂靠店铺id'
    ,affiliatedShopName string comment '挂靠店铺名'
    ,petsNumber string comment '宠物数量'
    ,baseServicePrice string comment '基础服务费用(每天)'
    ,baseServiceDistance string comment '商家设置基础费用包括的服务距离(m)'
    ,baseServicePets string comment '商家设置的基础费用包括的服务宠物数量'
    ,overServiceDistance string comment '超出服务距离(km)'
    ,overServiceDistancePrice string comment '超出服务距离费用(每公里)'
    ,overServicePetsPrice string comment '超出服务宠物数量加收的费用'
    ,categoryId string comment '服务类型， 对应表om_dic_pet_carer_service_category 中的category_id.'
    ,affiliatedUserId string comment '挂靠用户Id'
    ,settlementCycle string comment '结算周期: 订单确认完成， 多久进行结算。 目前是 t+7t+2'
    ,refundAmount string comment '退款金额'
    ,splitStatus string comment 'None'
    ,splitFailReason string comment 'None'
    ,splitCallbackTime string comment 'None'
    ,newCustomerOrder string comment '新客户首单'
    ,verifyTime string comment '核销时间'
    ,scene string comment '订单场景: 比如在权益卡中有 特价专区， 好物专区
      {@link com.meow.platform.enu'
    ,consignmentTaskId string comment '批量任务id'
    ,exchangeCode string comment '激活码'
    ,exchangeStatus string comment '{@link ExchangeStatusEnum}'
    ,effectiveTime string comment 'None'
    ,exchangeTime string comment 'None'
    ,taskCreatorId string comment 'None'
) comment '' 
stored as parquet
tblproperties ('parquet.compression' = 'snappy');

load data inpath '/cpp_data/mongo/platform_core_order/equity_order_info/full' overwrite into table s_mongo_platform_core_order_equity_order_info partition(ds = '$(date)s'); 