create table if not exists s_mongo_platform_shop_management_shop (
    id string comment '店铺id'
    ,shopCode string comment '店铺code'
    ,userId string comment '用户id'
    ,merchantId string comment '商家id'
    ,shopName string comment '店铺名称'
    ,shopImgs string comment '店铺相册 - 照片'
    ,shopVideos string comment '店铺相册 - 视频'
    ,coverUrl string comment '店铺封面url'
    ,lon string comment '商家具体位置 经度'
    ,lat string comment '商家具体位置 维度'
    ,geoSpatial string comment '地理信息 实现规范：RFC 7946 GeoJson
   
    @see <a href = "https:geo'
    ,geohash string comment 'geohash编码'
    ,province string comment '商家所属省'
    ,provinceCode string comment '商家所属省code'
    ,city string comment '商家所属城市'
    ,cityCode string comment '商家所属省code'
    ,county string comment '商家所属区县'
    ,countyCode string comment '商家所属区县code'
    ,address string comment '商家详细地址'
    ,divisionsCode string comment '商家地址行政区划代码 《GBT2260 中华人民共和国行政区划代码》'
    ,serviceTel string comment '客服电话'
    ,shopIntroduce string comment '店铺介绍'
    ,shopFacility string comment '店面设施'
    ,closed string comment '是否闭店'
    ,shopType string comment '店铺类型{@link com.meow.platform.enums.shop.ShopType}'
    ,shopStatus string comment '店铺状态 {@link com.meow.platform.enums.shop.ShopStatus}'
    ,shopAuditStatus string comment '店铺审核状态 {@link com.meow.platform.enums.shop.ShopAuditStatus}'
    ,starFlag string comment '是否星选'
    ,blankFlag string comment '是否黑名单'
    ,recommend string comment '是否推荐'
    ,isMeetGift string comment '是否预约有礼'
    ,delFlag string comment '删除标识'
    ,shopOwnerInfo string comment '店铺所属人信息'
    ,shopOpenTime string comment '店铺营业时间 {@link ShopOpenTime}'
    ,shopVip string comment '店铺VIP信息 {@link ShopVipInfo}'
    ,businessScopes string comment '店铺经营范围（系统分类）'
    ,shopStatisticsInfo string comment '店铺统计信息'
    ,createTime string comment '创建时间'
    ,updateTime string comment '修改时间'
    ,distance string comment '距离'
    ,settlementInfo string comment '店铺结算信息'
    ,recommendStartTime string comment 'None'
    ,recommendEndTime string comment 'None'
    ,recommendEffectiveDistance string comment 'None'
    ,recommendTransregionalDistance string comment 'None'
    ,isIndependentManagement string comment 'None'
    ,parentId string comment 'None'
    ,managerPhone string comment 'None'
    ,isBindAccount string comment '开户状态'
    ,shopAccountType string comment '账户类型'
    ,registerReason string comment '开通个人户原因'
    ,registerOperateSource string comment '开户操作来源'
    ,registerOperateTime string comment '开通个人户时间'
    ,registerOperateUser string comment '开通操作人员'
    ,companyName string comment '公司名称'
    ,usci string comment '社会统一信用代码'
    ,legalPersonName string comment '法人姓名'
) comment '' 
stored as parquet
tblproperties ('parquet.compression' = 'snappy');

load data inpath '/cpp_data/mongo/platform_shop_management/shop/full' overwrite into table s_mongo_platform_shop_management_shop partition(ds = '$(date)s'); 