create table if not exists s_mongo_platform_core_order_order_refund_info (
    id string comment '订单退款id'
    ,refundOrderNo string comment '退款订单编号'
    ,orderNo string comment '订单编号'
    ,afterSaleNo string comment '售后单号'
    ,payOrderNo string comment '支付订单编号'
    ,orderType string comment '订单类型，GENERAL_ORDER：普通商品订单，SERVICE_ORDER：服务商品订单'
    ,refundStatus string comment '退款状态，10：未退款，20：受理中，30：退款成功，40：退款失败'
    ,payUserId string comment '支付用户id'
    ,payUserWalletId string comment '支付用户钱包id'
    ,payUserName string comment '支付用户名称'
    ,merchantId string comment '商户id'
    ,merchantUserId string comment '商家用户id'
    ,merchantWalletId string comment '商家钱包id'
    ,chainShopWalletId string comment '连锁店铺钱包id 只有在连锁店铺下单时 才有该字段'
    ,merchantContractNo string comment '商家三方账户号'
    ,shopId string comment '店铺id'
    ,payType string comment '支付方式，WX：微信，ZFB：支付宝'
    ,payServiceType string comment '支付业务类型: WECHAT_JSGZH:微信公众号支付， WECHAT_JSXCX:微信小程序支付， ALIPAY_A'
    ,gatePaySerialNo string comment '第三方支付流水单号'
    ,gateRefundNo string comment '第三方退款单号'
    ,orderAmount string comment '订单交易金额'
    ,refundAmount string comment '退款金额'
    ,marketingRefundAmount string comment '营销退款金额'
    ,gateRefundAmount string comment '三方退款金额'
    ,refundApplyUser string comment '退款申请人'
    ,refundSource string comment '退款来源'
    ,fullRefundFlag string comment '全额退款标志，1：完整退款，2：非完整退款'
    ,refundReason string comment '退款原因'
    ,marketingAmount string comment 'None'
    ,totalMarketingAmount string comment 'None'
    ,marketingInfos string comment 'None'
    ,refundCompleteTime string comment '退款完成时间'
    ,createTime string comment '创建时间'
    ,updateTime string comment '更新时间'
) comment '' 
stored as parquet
tblproperties ('parquet.compression' = 'snappy');

load data inpath '/cpp_data/mongo/platform_core_order/order_refund_info/full' overwrite into table s_mongo_platform_core_order_order_refund_info partition(ds = '$(date)s'); 