create table if not exists dwd_ther_case_df(
    id bigint comment 'case_id'
    ,case_no bigint comment '病例单号'
    ,store_id bigint comment '门店id'
    ,merchant_id bigint comment '商家id'
    ,registration_id bigint comment '挂号表id'
    ,member_id bigint comment '会员id'
    ,doctor_id bigint comment '医生id'
    ,doctor_no bigint comment '医生编码'
    ,pet_id bigint comment '宠物id'
    ,chief_complaint string comment '主诉'
    ,past_history string comment '既往史：1-无，2-过敏史，3-慢性病史，4-其他'
    ,past_description string comment '既往史描述'
    ,disease_level string comment '病情等级：1-危重，2-一级，3-二级，4-三级'
    ,weight double comment '重量'
    ,body_temperature double comment '体温'
    ,heart_rate double comment '心率'
    ,respiratory_rate double comment '呼吸频率'
    ,blood_pressure double comment '血压'
    ,bcs double comment 'bcs评分'
    ,crt double comment 'crt评分'
    ,medical_examine string comment '体格检查描述'
    ,diagnosis_disease string comment '诊断描述'
    ,advice string comment '医嘱'
    ,diagnosis string comment '病情诊断'
    ,diagnosis_mark string comment '诊断拟是否勾选：1：勾选，0：未勾选'
    ,disease_classify_id_str string comment '疾病分类id集合，以/分隔'
    ,file_id_str string comment '附件id集合'
)
paritioned by (ds string comment '日期')
comment '病例表';