create table if not exists s_mongo_platform_pet_growth_management_user_remind (
    id string comment 'None'
    ,type string comment '类型：系统提醒-SYSTEM、用户自定义提醒：USER'
    ,userId string comment '提醒用户id'
    ,petId string comment '宠物id'
    ,title string comment '提醒标题'
    ,templateId string comment '系统提醒模版 id（为系统提醒时必须）'
    ,openStatus string comment '关闭状态 true开启 false关闭'
    ,remindCycleType string comment '提醒周期类型：仅一次-ONCE、每天-DAY、每周-WEED、每月-MONTH、每年-YEAR、自定义天数-CUSTOM'
    ,remindCycleDays string comment '自定义提醒周期（天数）'
    ,remindTime string comment '计划时间'
    ,nextRemindTime string comment '下次计划时间'
    ,firstDesc string comment '首次预设文案'
    ,guideDesc string comment '提醒引导文案'
    ,shareDesc string comment '相关小贴士'
    ,firstRemindDays string comment '首次提醒天数'
    ,marketingDesc string comment '营销文案'
    ,jumpUrl string comment '跳转链接'
    ,eventId string comment '事件Id 纪念日对应的事件记录表Id'
    ,remindNumber string comment '提醒次数'
    ,specialMark string comment '特殊标志'
    ,sn string comment '等级 1代表S 2代表A 3代表B'
    ,notice string comment '是否通知'
    ,noticeAdvanceDays string comment '通知提前天数（0-当天，1-提前1天，2-提前2天，3-提前三天）'
    ,noticeTime string comment '通知时间'
    ,nextNoticeTime string comment '下次通知时间'
    ,editFlag string comment '是否编辑过'
    ,delFlag string comment '删除标识'
    ,createTime string comment '创建时间'
    ,updateTime string comment '更新时间'
) comment '' 
stored as parquet
tblproperties ('parquet.compression' = 'snappy');

load data inpath '/cpp_data/mongo/platform_pet_growth_management/user_remind/full' overwrite into table s_mongo_platform_pet_growth_management_user_remind partition(ds = '$(date)s'); 