create table if not exists s_mongo_platform_product_management_service_product (
    id string comment '服务商品id'
    ,title string comment '商品标题'
    ,description string comment '商品描述'
    ,productCategory string comment '服务商品分类'
    ,shopCustomCategory string comment '店铺自定义分类'
    ,shop string comment '商品所在店铺'
    ,productTags string comment '商品标签列表'
    ,productPictureProductObjectStorags string comment '商品展示图片列表'
    ,productDetailText string comment '商品详情文本'
    ,productDetailObjectStorages string comment '商品详情列表，图片或者视频'
    ,buyNotes string comment '购买须知'
    ,reservationNotes string comment '预约须知'
    ,expiryDate string comment '有效期 单位：天'
    ,sn string comment '店铺内排序'
    ,saleState string comment '商品销售状态【上架、下架】'
    ,putOnSaleDate string comment '商品上架时间'
    ,auditState string comment '审核状态'
    ,approvedDate string comment '审核通过时间'
    ,createDate string comment '创建日期'
    ,updateDate string comment '修改日期'
    ,delFlag string comment '逻辑删除标签 false:未删除，true:已删除'
    ,serviceAdaptation string comment '服务商品个性化属性'
    ,serviceAttribute string comment '服务商品附加属性'
    ,geoJsonPoint string comment 'None'
    ,brandSnapshot string comment '品牌快照'
    ,purchaseRules string comment '购买规则'
    ,purchaseRestrictions string comment '购买限制'
    ,specialOfferState string comment '特惠状态'
    ,reviewReason string comment '待复核原因'
    ,kindTips string comment '温馨提示'
    ,productSortInfo string comment '排序信息'
) comment '' 
stored as parquet
tblproperties ('parquet.compression' = 'snappy');

load data inpath '/cpp_data/mongo/platform_product_management/service_product/full' overwrite into table s_mongo_platform_product_management_service_product partition(ds = '$(date)s'); 